export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';

export const FORM_FIELD_CHANGE = 'FORM_FIELD_CHANGE';
export const FORM_VALIDATION = 'FORM_VALIDATION';
export const FORM_CLEAN = 'FORM_CLEAN';

// export const USER_LOGOUT = 'USER_LOGOUT';
// export const USER_LOGOUT = 'USER_LOGOUT';
