export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTRATION_START = 'USER_REGISTRATION_START';
export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS';
export const USER_REGISTRATION_ERROR = 'USER_REGISTRATION_ERROR';

export const FORM_FIELD_CHANGE = 'FORM_FIELD_CHANGE';
export const FORM_VALIDATION = 'FORM_VALIDATION';
export const CHANGE_TYPE_FORM = 'CHANGE_TYPE_FORM';
export const FORM_CLEAN = 'FORM_CLEAN';

export const ASYNC_VALIDATION_START = 'ASYNC_VALIDATION_START';
export const ASYNC_VALIDATION_SUCCESS = 'ASYNC_VALIDATION_SUCCESS';
export const ASYNC_VALIDATION_ERROR = 'ASYNC_VALIDATION_ERROR';

export const FETCH_ALBUMS = 'FETCH_ALBUMS';

export const LOAD_NEW_PLAYING_INDEX = 'LOAD_NEW_PLAYING_INDEX';
export const PLAY_SONG = 'PLAY_SONG';
export const ON_LOAD_START = 'ON_LOAD_START';
export const ON_PLAY = 'ON_PLAY';
export const ON_PAUSE = 'ON_PAUSE';
export const ON_LOADED_METADATA = 'ON_LOADED_METADATA';
export const ON_TIME_UPDATE = 'ON_TIME_UPDATE';
export const ON_VOLUME_CHANGE = 'ON_VOLUME_CHANGE';
export const TOGGLE_VOLUME = 'TOGGLE_VOLUME';
export const TOGGLE_REPEAT = 'TOGGLE_REPEAT';
export const TOGGLE_SHUFFLE = 'TOGGLE_SHUFFLE';
export const SEARCH_TRACK = 'SEARCH_TRACK';

export const TOGGLE_LIKE_TRACK = 'TOGGLE_LIKE_TRACK';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';

export const ON_SELECT_NEW_ALBUM = 'ON_SELECT_NEW_ALBUM';
