export const USER_LOGIN = 'USER_LOGIN';
export const USER_REGISTRATION = 'USER_REGISTRATION';
export const USER_LOGOUT = 'USER_LOGOUT';

export const FORM_FIELD_CHANGE = 'FORM_FIELD_CHANGE';
export const FORM_VALIDATION = 'FORM_VALIDATION';
export const CHANGE_TYPE_FORM = 'CHANGE_TYPE_FORM';
export const FORM_CLEAN = 'FORM_CLEAN';

export const ASYNC_VALIDATION_START = 'ASYNC_VALIDATION_START';
export const ASYNC_VALIDATION_SUCCESS = 'ASYNC_VALIDATION_SUCCESS';
export const ASYNC_VALIDATION_ERROR = 'ASYNC_VALIDATION_ERROR';

// export const USER_LOGOUT = 'USER_LOGOUT';
// export const USER_LOGOUT = 'USER_LOGOUT';
